### ISSUE TITLE
Compatibility with material icon plugin

### ISSUE THREAD

**Issue by borisrorsvort** [PaperTiger/figma-dark-ui#10]
If you have the material icon figma plus plugin the icons appear gray instead of white
<img width="486" alt="Screenshot 2019-05-07 at 08 33 16" src="https://user-images.githubusercontent.com/39081/57276859-0d804100-70a3-11e9-9687-e10aa878b725.png">

**Comment by mirkosantangelo** [comment]
This may need to be reviewed by the author of the plugin. @cdes
