### ISSUE TITLE
Inverted Colour Styles

### ISSUE THREAD

**Issue by dave-hawkins** [PaperTiger/figma-dark-ui#11]
Plugin seems to invert my colour styles, heres an example with dark mode disabled:
![Screenshot 2019-05-07 at 10 35 11](https://user-images.githubusercontent.com/14091192/57289836-0ca3db00-70b4-11e9-9274-7c3ee21816af.png)

and enabled:
![Screenshot 2019-05-07 at 10 36 25](https://user-images.githubusercontent.com/14091192/57289840-12012580-70b4-11e9-95bf-e8524497b42c.png)

**Comment by AmiciA** [comment]
I actually only notice this issue with gradients and photos, as below:

**gradient**
![image](https://user-images.githubusercontent.com/437844/57290460-06cbeb00-70f0-11e9-8efc-80a73b972fcb.png)

**photo**
![image](https://user-images.githubusercontent.com/437844/57290697-8063d900-70f0-11e9-8b85-6628f31972de.png)

**Comment by mirkosantangelo** [comment]
@dave-hawkins This should be fixed on 0.0.8.
