### ISSUE TITLE
Inverted gradients at Dark mode

### ISSUE THREAD

**Issue by imfrombristol** [PaperTiger/figma-dark-ui#12]
When I switched on the Dark Mode. the plugin changed the appearance of my gradients at Local Color Library. Now the Gold Gradient appeared in the blue colors. 
![image](https://user-images.githubusercontent.com/30962230/57292083-2dbef880-70c1-11e9-8582-d624ded0eda8.png)

**Comment by mirkosantangelo** [comment]
@imfrombristol This should be fixed on 0.0.8.
