### ISSUE TITLE
Dark mode for rulers

### ISSUE THREAD

**Issue by misolori** [PaperTiger/figma-dark-ui#13]
It appears that rulers do not inherit the dark mode style:

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/35271042/57335555-d24c3500-70d7-11e9-80e8-212a05c39081.png">

**Comment by mirkosantangelo** [comment]
Hey Miguel! Unfortunately rulers are painted via the canvas element. Didn't find any way to change them.
