### ISSUE TITLE
Share bar in prototype not in dark mode

### ISSUE THREAD

**Issue by edward-battistini** [PaperTiger/figma-dark-ui#14]
When I open a prototype using the "play" in figma 
Then the ShareBar is not in dark mode

<img width="1979" alt="Screenshot 2019-05-10 at 10 13 01" src="https://user-images.githubusercontent.com/19345730/57516285-5981ee80-730c-11e9-960e-0f447eb20316.png">

**Comment by mirkosantangelo** [comment]
@edward-battistini This should be fixed on 0.0.8.
