### ISSUE TITLE
Search asset in left panel needs more contrast

### ISSUE THREAD

**Issue by edward-battistini** [PaperTiger/figma-dark-ui#15]
When i want to search assets in my library
I can't really see my inputed text in the search field 

<img width="307" alt="Screenshot 2019-05-10 at 10 15 30" src="https://user-images.githubusercontent.com/19345730/57516400-91893180-730c-11e9-9d3a-27b227afca39.png">

**Comment by mirkosantangelo** [comment]
@edward-battistini This should be fixed on 0.0.8.
