### ISSUE TITLE
Rulers are bright

### ISSUE THREAD

**Issue by choomaque** [PaperTiger/figma-dark-ui#6]
after update, rulers (which are shown by Shift + R combination) appears to be bright

<img width="345" alt="image" src="https://user-images.githubusercontent.com/39616153/53683586-2c610080-3d0b-11e9-8f71-4b3267a4191d.png">

Using add-on within Figma Plus on top of Figma Desktop 68 build 5 on macOS Mojave 10.14.3

**Comment by mirkosantangelo** [comment]
Unfortunately the Ruler Style can't be changed at the moment.
